# Site
name: "Summer of Bitcoin Blog"
title: "Summer of Bitcoin"
description: "Official blog of Summer of Bitcoin"
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: ''
disqus: false
comments: false
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Summer of Bitcoin:
    name: Summer of Bitcoin
    display_name: Summer of Bitcoin Team
    avatar: "assets/images/favicon.png"
    email: hello@summerofbitcoin.org
    web: https://summerofbitcoin.org
    twitter: https://x.com/summerofbitcoin
    description: "Team behind Summer of Bitcoin, a global summer internship program for bitcoin open-source development and design."
  Sivaram D:
    name: Sivaram D
    display_name: Sivaram Dhakshinamoorthy
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/siv2r
    description: "Summer of Bitcoin Batch of 2021, worked on libsecp256k1."
  Priyansh Rastogi:
    name: Priyansh Rastogi
    display_name: Priyansh Rastogi
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/priyansh_tweet
    description: "Summer of Bitcoin Batch of 2021, worked on mempool.space"
  Pavan Joshi:
    name: Pavan Joshi
    display_name: Pavan Joshi
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/pavanj1620
    description: "Summer of Bitcoin Batch of 2022, worked on Alby"
  César Alvarez Vallero:
    name: César Alvarez Vallero
    display_name: César Alvarez Vallero
    avatar: 'assets/images/avatar.png'
    twitter: https://twitter.com/csralvall
    description: "Summer of Bitcoin Batch of 2022, worked on BDK"
  Goutam Verma:
    name: Goutam Verma
    display_name: Goutam Verma
    avatar: 'assets/images/avatar.png'
    twitter: https://twitter.com/Goutamv69080354
    description: "Summer of Bitcoin Batch of 2022, worked on Eclair"
  Jing Liu:
    name: Jing Liu
    display_name: Jing Liu
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/6chinggg
    description: "Summer of Bitcoin Batch of 2022, worked on Bitcoin Core"
  Pedro Felix:
    name: Pedro Felix
    display_name: Pedro Felix
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/logosstone
    description: "Summer of Bitcoin Batch of 2022, worked on BDK"
  Arnab Sen:
    name: Arnab Sen
    display_name: Arnab Sen
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/arnabsen1729
    description: "Summer of Bitcoin Batch of 2021, worked on Bitcoin Core"
  Omer Yacine:
    name: Omer Yacine
    display_name: Omer Yacine
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/summerofbitcoin
    description: "Summer of Bitcoin Batch of 2022, worked on Eye of Satoshi"
  Aniketh Paul:
    name: Aniketh Paul
    display_name: Aniketh Paul
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/Alphooor
    description: "Summer of Bitcoin Batch of 2023, worked on Eye of Satoshi"
  Sandipan Dey:
    name: Sandipan Dey
    display_name: Sandipan Dey         
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/sandipndev
    description: "Summer of Bitcoin Batch of 2021, worked on BDK"
  Anmol Sharma:
    name: Anmol Sharma
    display_name: Anmol Sharma
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/theanmolsharma_
    description: "Summer of Bitcoin Batch of 2022, worked on bcoin"
  Sanjay Singh Rajpoot:
    name: Sanjay Singh Rajpoot
    display_name: Sanjay Singh Rajpoot
    avatar: 'assets/images/avatar.png'
    twitter: https://x.com/summerofbitcoin
    description: "Summer of Bitcoin Batch of 2022, worked on RTL"
  satoshi:
    name: Satashi Nakamoto
    display_name: Satoshi    
    avatar: 'assets/images/avatar.png'
    email: satoshin@gmx.com
    web: https://bitcoin.org
    twitter: https://twitter.com/satoshi
    description: "Inventor of bitcoin."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
